name: build

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Build application
        run: ./build.ps1
        shell: pwsh

      - uses: actions/upload-artifact@v4.3.6
        with:
          name: SecretManagement.DevolutionsServer
          path: ./package/SecretManagement.DevolutionsServer
