name: release

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    environment: psgallery-publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Install module dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Microsoft.Powershell.SecretManagement
          Install-Module Devolutions.Hub

      - name: Build application
        run: ./build.ps1
        shell: pwsh

      - name: Publish application
        run: Publish-Module -Path ./package/SecretManagement.DevolutionsHub -NuGetApiKey "${{ secrets.PSGALLERY_API_KEY }}" -Verbose
        shell: pwsh
