name: Publish PowerShell Module

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    environment: psgallery-publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Check out Devolutions/actions
        uses: actions/checkout@v3
        with:
          repository: Devolutions/actions
          ref: master
          token: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}
          path: ./.github/workflows

      - name: Install module dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Microsoft.Powershell.SecretManagement
          Install-Module Devolutions.Hub

      - name: Build application
        uses: ./.github/workflows/powershell-build

      - name: Publish application
        uses: ./.github/workflows/powershell-publish
        with:
          nugetApiKey: ${{ secrets.PSGALLERY_API_KEY }}
          modulePath: ./package/SecretManagement.DevolutionsHub
